    
spring:
  profiles:
    active: "@activatedProperties@"
  output:
    ansi:
      enabled: detect
      
jasypt:
  encryptor:
    password: ${APP_ENCRYPTION_PASSWORD}
 
security:
  user:
    name: admin
    password: ENC(E4nbtM4lNXAYJ1Z2HwwpAxwVlIrVgroS)
    
---
spring:
  profiles: dev
  application:
    name: App-Dev
  datasource:
    url: jdbc:mysql://localhost:3306/vir?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080

---

spring:
  profiles: prod
  application:
    name: App-Prod
  datasource:
    url: jdbc:mysql://localhost:3306/vir?useSSL=false
    username: root
    password: ENC(/98CfxmsjKBW5oZsLkLlmw==)
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
server:
  port: 5000