    
spring:
  profiles:
    active: "@activatedProperties@"
  output:
    ansi:
      enabled: detect
  http:
    multipart:
      max-file-size: 50485760
      max-request-size: 50485760
      
jasypt:
  encryptor:
    password: ${APP_ENCRYPTION_PASSWORD}
  
---
spring:
  profiles: dev
  application:
    name: App-Dev
  datasource:
    url: jdbc:mysql://localhost:3306/vir?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
security:
  user:
    name: admin
    password: admin
    
server:
  port: 8080
---

spring:
  profiles: prod
  application:
    name: App-Prod
  datasource:
    url: ENC(H5rcrCkCEEH2hxqNtVfXLTn7L8ujXX2mwSGwLSn7xPYnNCSbCS24AJTSblTMesmTlYooIoqJxAV6UsnhmDLbKoqXVP7vo5sXu+TjRd4hrkblDviAHYuaAw==)
    username: ENC(UTkNIxV6ppTay6dw1Y2Ko7wslhPUEBlt)
    password: ENC(e727rLvbmnoUNdmsXj7CpZPWtklCNXW0)
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  user:
    name: ENC(FDR1l4UOnbo2E7qq1ByDzg==)
    password: ENC(E4nbtM4lNXAYJ1Z2HwwpAxwVlIrVgroS)
        
server:
  port: 5000